# ubuntu
# - setup your runtime (eg. dotnet, node, etc.)
# - check out your source  https://github.com/marketplace/actions/checkout

name: My first workflow

# trigger
on: 
- push

jobs:
    # give job a name
    my-first-job:
        # runner using ubuntu to run
        # github action runners https://github.com/actions/runner-images#available-environments for others. some require payment
        runs-on: ubuntu-latest    

        # steps of this job
        steps:
        - name: echo the date
          run: echo "hello, Github Action $(date)"

        - name: list directory before checkout
          run: ls - l

        - name: checkout source code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.base_ref }}

        - name: list directory
          run: ls - l

        - name: echo the git branch
          run: echo "hello, the Github branch is ${{ github.ref_name }}, ${{ github.repositoryUrl }}"

          # https://github.com/marketplace/actions/cowsays
        - name: echo the cow says
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: "I am on branch ${{ github.base_ref}}"
            color: 'red'


        # to install dotnet on ubuntu, https://github.com/marketplace/actions/setup-dotnet
  